// Best Buds user activity types
export const USER_ACTIVITY_TYPES = {
    APP_VISIT: "APP_VISIT",
    DISPENSARY_VIEW: "DISPENSARY_VIEW",
    AREA_SEARCH: "AREA_SEARCH",
    ARTICLES_VIEW: "ARTICLES_VIEW",
    PRODUCTS_VIEW: "PRODUCTS_VIEW",
    SAFETY_VIEW: "SAFETY_VIEW",
    EDUCATION_VIEW: "EDUCATION_VIEW"
};